import{a as c,S as d,i as n}from"./assets/vendor-BLkLXWwN.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();c.defaults.baseURL="https://pixabay.com";const m="55024434-f37333710f698bb54909d1b68";function h(i){return c.get("/api/",{params:{key:m,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data.hits)}const f=document.querySelector(".gallery"),u=document.querySelector(".loader");let p=new d(".gallery a",{captionsData:"alt",captionsDelay:250});function g(){f.innerHTML=""}function y(i){const o=i.map(t=>`<li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" width="360" height="200" />
      </a>
      <ul class="info-list">
        <li class="info-item"><h3 class="info-title">Likes</h3><p class="info-text">${t.likes}</p></li>
        <li class="info-item"><h3 class="info-title">Views</h3><p class="info-text">${t.views}</p></li>
        <li class="info-item"><h3 class="info-title">Comments</h3><p class="info-text">${t.comments}</p></li>
        <li class="info-item"><h3 class="info-title">Downloads</h3><p class="info-text">${t.downloads}</p></li>
      </ul>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),p.refresh()}function L(){u.classList.remove("hidden")}function l(){u.classList.add("hidden")}const b=document.querySelector(".form");b.addEventListener("submit",w);function w(i){i.preventDefault();const o=i.target.elements["search-text"].value.trim();if(o===""){n.warning({title:"Warning!",message:"Please enter a search term before submitting.",position:"topRight",timeout:3e3,pauseOnHover:!0});return}g(),L(),h(o).then(t=>{if(l(),t.length===0){n.error({title:"Sorry!",message:"There are no images matching your search query. Please try again!",position:"topRight"});return}y(t)}).catch(t=>{l(),console.error(t),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})})}
//# sourceMappingURL=index.js.map
