import{a as c,S as d,i as n}from"./assets/vendor-BLkLXWwN.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();c.defaults.baseURL="https://pixabay.com";const m="55024434-f37333710f698bb54909d1b68";async function p(o){return(await c.get("/api/",{params:{key:m,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),u=document.querySelector(".loader");let h=new d(".gallery a",{captionsData:"alt",captionsDelay:250});function y(){f.innerHTML=""}function g(o){const i=o.map(t=>`<li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" width="360" height="200" />
      </a>
      <ul class="info-list">
        <li class="info-item"><h3 class="info-title">Likes</h3><p class="info-text">${t.likes}</p></li>
        <li class="info-item"><h3 class="info-title">Views</h3><p class="info-text">${t.views}</p></li>
        <li class="info-item"><h3 class="info-title">Comments</h3><p class="info-text">${t.comments}</p></li>
        <li class="info-item"><h3 class="info-title">Downloads</h3><p class="info-text">${t.downloads}</p></li>
      </ul>
    </li>`).join("");f.insertAdjacentHTML("beforeend",i),h.refresh()}function L(){u.classList.remove("hidden")}function l(){u.classList.add("hidden")}const b=document.querySelector(".form");b.addEventListener("submit",w);async function w(o){o.preventDefault();const i=o.target.elements["search-text"].value.trim();if(i===""){n.warning({title:"Warning!",message:"Please enter a search term before submitting.",position:"topRight",timeout:3e3,pauseOnHover:!0});return}y(),L();try{const{hits:t}=await p(i);if(l(),t.length===0){n.error({title:"Sorry!",message:"There are no images matching your search query. Please try again!",position:"topRight"});return}g(t)}catch(t){l(),console.error(t),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}}
//# sourceMappingURL=index.js.map
