import{a as h,S as v,i}from"./assets/vendor-BLkLXWwN.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();h.defaults.baseURL="https://pixabay.com";const q="55024434-f37333710f698bb54909d1b68";async function m(r,o){return(await h.get("/api/",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more");let x=new v(".gallery a",{captionsData:"alt",captionsDelay:250});function M(){y.innerHTML=""}function L(r){const o=r.map(e=>`<li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" width="360" height="200" />
      </a>
      <ul class="info-list">
        <li class="info-item"><h3 class="info-title">Likes</h3><p class="info-text">${e.likes}</p></li>
        <li class="info-item"><h3 class="info-title">Views</h3><p class="info-text">${e.views}</p></li>
        <li class="info-item"><h3 class="info-title">Comments</h3><p class="info-text">${e.comments}</p></li>
        <li class="info-item"><h3 class="info-title">Downloads</h3><p class="info-text">${e.downloads}</p></li>
      </ul>
    </li>`).join("");y.insertAdjacentHTML("beforeend",o),x.refresh()}function w(){g.classList.remove("hidden")}function c(){g.classList.add("hidden")}function b(){p.classList.remove("hidden")}function u(){p.classList.add("hidden")}let d="",n=1,f=0;const S=15,P=document.querySelector(".form"),$=document.querySelector(".load-more");P.addEventListener("submit",B);$.addEventListener("click",R);async function B(r){r.preventDefault(),w(),u();const o=r.target.elements["search-text"].value.trim();if(d=o,n=1,o===""){i.warning({title:"Warning!",message:"Please enter a search term before submitting.",position:"topRight"}),c();return}M();try{const{hits:e,totalHits:a}=await m(d,n);if(f=a,e.length===0){i.error({title:"Sorry!",message:"There are no images matching your search query.",position:"topRight"});return}L(e),n*S<f?b():i.info({message:"We're sorry, but you've reached the end of search results."})}catch(e){console.error(e),i.error({message:"Something went wrong."})}finally{c()}}async function R(){u(),w();try{n+=1;const{hits:r}=await m(d,n);if(r.length===0){i.info({message:"We're sorry, but you've reached the end of search results."});return}L(r);const{height:o}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),n*S>=f?(u(),i.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch(r){console.error(r),i.error({message:"Something went wrong."})}finally{c()}}
//# sourceMappingURL=index.js.map
